### ISSUE TITLE
Error en InstaladorControlador

### ISSUE THREAD

**Issue by marrokin** [webcol/Calima#6]
Path:
 Calima/mvc/controladores/instaladorControlador.php
Line:89
public function paso1($proyecto, $analytics, $hostbd, $nombrebd, $usuariobd, **$usuariobd,** $clavebd, $config)

Parametro $usuariobd duplicado en la funcion publica paso1

**Comment by webcol** [comment]
Muchas Gracias marrokin ya mismo lo actualizamos
